import java.time.*
import java.time.format.DateTimeFormatter

pipeline {
    agent any
    environment {
        DATE_NOW = ''
        DOCKER_TAG = ''
        REPOSITORY_URI = "backend-lista-compras"
        REPOSITORY_URI_APP = ''
    }

    stages {
        stage('Construir Tag') {
            steps {
                script {
                    def now = new Date()
                    DATE_NOW = now.format("yyMMdd.HHmm", TimeZone.getTimeZone('UTC'))
                    DOCKER_TAG = "$DATE_NOW.$BUILD_NUMBER"
                    REPOSITORY_URI_APP = "$REPOSITORY_URI:$DOCKER_TAG"
                    echo "Tag generado: ${REPOSITORY_URI_APP}"
                }
            }
        }

        stage('Desplegar con Docker Compose') {
            steps {
                sh """
                    CONTAINER_IMAGE=${REPOSITORY_URI_APP} docker compose -f ./devops/docker-compose.yml up -d --build
                    docker image prune -f
                """
            }
        }
    }
}
